services:
  - type: web
    name: wcbnw
    runtime: static
    rootDir: WCBNW-redesign
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
